import { Card } from './card';

export const CARDS: Card[] = [
  {'title': 'Banjo & Kazooie', 'order': 2.18},
  {'title': 'Bayonetta', 'order': 1.76},
  {'title': 'Bowser Jr.', 'order': 1.566},
  {'title': 'Bowser', 'order': 1.971},
  {'title': 'Byleth', 'order': 1.43},
  {'title': 'Captain Falcon', 'order': 2.552},
  {'title': 'Charizard', 'order': 2.2},
  {'title': 'Chrom', 'order': 2.145},
  {'title': 'Cloud', 'order': 2.167},
  {'title': 'Corrin', 'order': 1.595},
  {'title': 'Daisy', 'order': 1.595},
  {'title': 'Dark Pit', 'order': 1.828},
  {'title': 'Dark Samus', 'order': 1.654},
  {'title': 'Diddy Kong', 'order': 2.006},
  {'title': 'Donkey Kong', 'order': 1.873},
  {'title': 'Dr. Mario*', 'order': 1.397792},
  {'title': 'Duck Hunt', 'order': 1.793},
  {'title': 'Falco', 'order': 1.619},
  {'title': 'Fox', 'order': 2.402},
  {'title': 'Ganondorf', 'order': 1.34},
  {'title': 'Greninja', 'order': 2.288},
  {'title': 'Hero', 'order': 1.84},
  {'title': 'Ice Climbers (leader)', 'order': 1.53},
  {'title': 'Ice Climbers (partner)', 'order': 1.683},
  {'title': 'Ike', 'order': 1.507},
  {'title': 'Incineroar', 'order': 1.18},
  {'title': 'Inkling', 'order': 1.925},
  {'title': 'Isabelle', 'order': 1.48},
  {'title': 'Ivysaur', 'order': 1.595},
  {'title': 'Jigglypuff', 'order': 1.271},
  {'title': 'Joker', 'order': 2.06},
  {'title': 'Ken', 'order': 1.76},
  {'title': 'King Dedede', 'order': 1.496},
  {'title': 'King K. Rool', 'order': 1.485},
  {'title': 'Kirby', 'order': 1.727},
  {'title': 'Link', 'order': 1.534},
  {'title': 'Little Mac', 'order': 2.464},
  {'title': 'Lucario', 'order': 1.705},
  {'title': 'Lucas', 'order': 1.65},
  {'title': 'Lucina', 'order': 1.964},
  {'title': 'Luigi', 'order': 1.65},
  {'title': 'Mario', 'order': 1.76},
  {'title': 'Marth', 'order': 1.964},
  {'title': 'Mega Man', 'order': 1.602},
  {'title': 'Meta Knight', 'order': 2.09},
  {'title': 'Mewtwo', 'order': 2.255},
  {'title': 'Mii Brawler', 'order': 1.92},
  {'title': 'Mii Gunner', 'order': 1.37},
  {'title': 'Mii Swordfighter', 'order': 1.58},
  {'title': 'Min Min', 'order': 1.55},
  {'title': 'Mr. Game & Watch', 'order': 1.679},
  {'title': 'Ness', 'order': 1.609},
  {'title': 'Olimar', 'order': 1.617},
  {'title': 'Pac-Man', 'order': 1.672},
  {'title': 'Palutena', 'order': 2.077},
  {'title': 'Peach', 'order': 1.595},
  {'title': 'Pichu', 'order': 1.892},
  {'title': 'Pikachu', 'order': 2.039},
  {'title': 'Piranha Plant', 'order': 1.72},
  {'title': 'Pit', 'order': 1.828},
  {'title': 'R.O.B.', 'order': 1.725},
  {'title': 'Richter', 'order': 1.52},
  {'title': 'Ridley', 'order': 2.2},
  {'title': 'Robin', 'order': 1.265},
  {'title': 'Rosalina & Luma', 'order': 1.795},
  {'title': 'Roy', 'order': 2.145},
  {'title': 'Ryu', 'order': 1.6},
  {'title': 'Samus', 'order': 1.654},
  {'title': 'Sheik', 'order': 2.42},
  {'title': 'Shulk', 'order': 1.672},
  {'title': 'Simon', 'order': 1.52},
  {'title': 'Snake', 'order': 1.595},
  {'title': 'Sonic', 'order': 3.85},
  {'title': 'Squirtle', 'order': 1.76},
  {'title': 'Steve', 'order': 1.45},
  {'title': 'Terry', 'order': 1.72},
  {'title': 'Toon Link', 'order': 1.906},
  {'title': 'Villager', 'order': 1.397},
  {'title': 'Wario', 'order': 1.65},
  {'title': 'Wii Fit Trainer', 'order': 1.866},
  {'title': 'Wolf', 'order': 1.54},
  {'title': 'Yoshi', 'order': 2.046},
  {'title': 'Young Link', 'order': 1.749},
  {'title': 'Zelda', 'order': 1.43},
  {'title': 'Zero Suit Samus', 'order': 2.31},
];
